apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - FrontendConfig.yaml
  - ingress.yaml
  - SecretStore.yaml
  - ExternalSecret.yaml