apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    gcpsm:
      projectID: tumahela
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: development
          serviceAccountRef:
            name: demo-app