apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/

namespace: dev-demo-app

labels:
- pairs:
    Environment: dev
    Team: devops

patches:
- path: deployment-patch.yaml
- path: hpa-patch.yaml
- path: ingress-patch.yaml
- patch: |-
    - op: replace
      path: /metadata/name
      value: dev-demo-app
  target:
    kind: Namespace
    name: default
