name: Build-App-Image

on:
  workflow_call:
    inputs:
      PROJECT_ID:
        required: true
        type: string
      REGION:
        required: true
        type: string
      GAR_LOCATION:
        required: true
        type: string
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true

env:
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  REGION: ${{ inputs.REGION }}
  GAR_LOCATION: ${{ inputs.GAR_LOCATION }}

jobs:
  build_app_image:
    name: build_app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          
      # - name: Build, tag, and push image to ECR
      #   id: build-image
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     IMAGE_TAG: ${{ github.sha }}
      #   run: |
      #     docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest -f demo-app/Dockerfile .

      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags