name: Build-App-Image

on:
  workflow_call:
    inputs:
      PROJECT_ID:
        required: true
        type: string
      REGION:
        required: true
        type: string
      GAR_LOCATION:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string
      APPLICATION:
        required: true
        type: string
    secrets:
      GCP_SERVICE_ACCOUNT_KEY:
        required: true

env:
  PROJECT_ID: ${{ inputs.PROJECT_ID }}
  REGION: ${{ inputs.REGION }}
  GAR_LOCATION: ${{ inputs.GAR_LOCATION }}
  DOCKERFILE: ${{ inputs.DOCKERFILE }}
  APPLICATION: ${{ inputs.APPLICATION }}

jobs:
  build_app_image:
    name: build_app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build, tag, and push image to ECR
        id: build-image
        env:
          GAR_LOCATION: ${{ env.GAR_LOCATION }}
          GITHUB_SHA: ${{ github.sha }}
          APPLICATION: ${{ env.APPLICATION }}
        run: |
          docker build -f $DOCKERFILE -t $GAR_LOCATION/$APPLICATION:$GITHUB_SHA -t $GAR_LOCATION/$APPLICATION:latest .
          docker push --all-tags $GAR_LOCATION