name: Deploy Development

on:
  push:
    branches: ["main"]

jobs:
  build-app-image:
    uses: ./.github/workflows/build-app.yml
    with:
      PROJECT_ID: tumahela
      REGION: europe-west1
      GAR_LOCATION: europe-west1-docker.pkg.dev/tumahela/demo-app/demo-app
      DOCKERFILE: demo-app/Dockerfile
    secrets:
      GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_DEV }}

  deploy-app-infra:
    uses: ./.github/workflows/deploy-infra.yml
    with:
      TERAFORM_WORKSPACE: dev
      WORKING_DIRECTORY: demo-app/terraform
    secrets: inherit